# in profile
spring:  
  datasource:
    url: jdbc:mysql://localhost:3306/mockproject2
    username: root
    password: G3a3r3y3
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
