# in profile
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mockproject2
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none

app:
  jwt:
    secret: nosecret  
  